### ISSUE TITLE
Contributor Workflow

### ISSUE THREAD

**Issue by kathleeng77** [rgroves/project-bueller#3]
@rgroves 

I had some questions about the contributor workflow so I'm testing how to create an 'issue' at the same time. Please let me know if this is how I should go about it or if I should create separate issues for the following:

1. I struggled a bit between steps 2 and 3 of the contributor workflow. I think it was because I didn't change directory to the local repo that I had just cloned in order to be able to add the upstream. If this is correct, maybe there could be a little 'reminder' for the reader/contributor to 'cd project-bueller'  before showing how to add the upstream. If this is not correct, could you explain?

2. In step 4, which directory should I be in when I add/commit/push?  Does the working directory matter when you either add, commit, or push?

3. Also in step 4, what is the difference between:
    a) making two steps: 'git add file' and then later 'git commit -m "Change description"'
    b) one step: git commit -am "Change description"
When I didn't put 'git add filename' before 'git commit -am "Change description"', then it told me that I had changes that weren't being tracked yet.

4. In step 5, what is HEAD~X? I got an error saying this was invalid.

Thank you!! 😃

**Comment by rgroves** [comment]
1. Yes, you need to be in the repo directory before running the `git remote add` command. I have added a clarification to that step.

2. Your local working directory doesn't matter with an add/commit/push. A `git add` will only stage whatever you tell it to; a `git commit` will only commit what has been staged via `git add`; and a `git push` will push the local commit(s) regardless of the directory you're in locally (as long as you're still located somewhere within the repo's root directory).

3. There should be no difference, except for the obvious difference between the way those commands work: with `git add file` you'd be adding a single file vs adding *and committing* all dirty/changed files when using `git -am "..."`. You may not want to do `git -am` if you know that you don't want all dirty local changes staged.

I want to guess that you deleted the previous file and directory you had created and git is still tracking that, maybe? Did you start with a clean fork or did you delete the original directory and file that you had created? If the latter, did you use git rm to delete? If you run `git status` from anywhere inside your local repo, what does it show?

4. The X in that command would need to be changed to a number that represents the number of commits you want to "squash" in the rebase. Your change only had one commit so it wouldn't have been needed. If you had multiple commits you'd want to squash them into one clean, descriptive commit. 

For example, let says you are working on an issue that will take you a while to complete. You've been working for a few days and have already committed multiple changes to your local repo. When you've completed all of the changes required for the issue and all is working properly, let's say you end up with 8 commits. Following the contributor workflow, you would (from within your issue branch) create and checkout a release candidate branch. Then you'd use the `git rebase` command to squash all 8 of your commits into one clean, descriptive commit on that branch so that it is ready to be pushed back to origin (your fork) and a pull request created for upstream (the master repo). In this example, that would look like this:
```
# Let's say you were working on issue branch 001-add-calendar-filtering-by-venue
# lets be sure we are on our issue branch by checking it out
git checkout 001-add-calendar-filtering-by-venue
# create and checkout our release candidate branch
git branch 001-add-calendar-filtering-by-venue-rc
git checkout 001-add-calendar-filtering-by-venue-rc
# Squash the 8 commits into one clean, descriptive commit
git rebase -i HEAD~8
# Push changes back to origin (your fork of the master repo)
git push origin 001-add-calendar-filtering-by-venue-rc
# Then in github you would create the pull request
```

Hope that helps clarify. Let me know if there are other questions.

**Comment by kathleeng77** [comment]
Wow! Awesome stuff! Things are starting to click. Thank you!
